language: node_js
node_js:
  - "4.0"
  - "4.1"
  - "4.2"
  - "4.3"
  - "4.4"
  - "4.5"
  - "5.0"
  - "5.1"
  - "5.2"
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"
  - "5.7"
  - "5.8"
  - "5.9"
  - "5.10"
  - "5.11"
  - "6.0"
  - "6.1"
  - "6.2"
  - "6.3"
  - "6.4"
  - "6.6"
script:
  - node --stack-trace-limit=1000 --allow-natives-syntax ./tests/unittests.js
  - node --stack-trace-limit=1000 --allow-natives-syntax ./tests/integration.js
env: IMPRESS_MODE=test
