language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs-v1"
  - "iojs-v2"
  - "iojs-v3"
  - "4.0"
  - "4.1"
  - "4.2"
  - "5.0"
  - "5.1"
  - "5.2"
  - "5.3"
  - "5.4"
  - "5.5"
script:
  - node --stack-trace-limit=1000 --allow-natives-syntax ./tests/unittests.js
  - node --stack-trace-limit=1000 --allow-natives-syntax ./tests/integration.js
env: IMPRESS_MODE=test
